name: python_app_image_publication
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop
jobs:
  create_docker_image:
    runs-on: self-hosted
    steps:
      - name: installing runner dependencies
        run: |
          pwd
          ls
          