name: python_app_image_publication
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  # runner_dependencies:
  #   runs-on: [self-hosted, linux, git-runner]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: installing runner dependencies
  #       run: |
  #        bash dependencies.sh
  testing_python:
      runs-on: [self-hosted, linux, git-runner]
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
  
  building_docker_image:
    runs-on: [self-hosted, git-runner]
    needs: [testing_python]
    steps:
      - name: building docker image
        run: |
         sudo docker build -t shubhamborkar/pythonapp:v1.0 ./
  
  publishing_docker_image:
    runs-on: [self-hosted, git-runner]
    #if: ${{ always() }}        ...runs the job regardless of other jobs being successful
    needs: [building_docker_image]
    steps:
      - name: publishing docker image
        run: |
          sudo chmod 666 /var/run/docker.sock
          cat docpasswd.txt | docker login --username shubhamborkar --password-stdin
          sudo docker push shubhamborkar/myapp:v1.0
