name: python_app_image_publication
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  runner_dependencies:
    runs-on: [self-hosted, linux, git-runner]
    steps:
      - uses: actions/checkout@v2
      - name: installing runner dependencies
        run: |
         bash dependencies.sh
  
  building_docker_image:
    runs-on: [self-hosted, git-runner]
    steps:
      - name: installing runner dependencies
        run: |
         sudo docker build -t shubhamborkar/pythonapp:v1.0
          