name: python_app_image_publication
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  # runner_dependencies:
  #   runs-on: [self-hosted, linux, git-runner]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: installing runner dependencies
  #       run: |
  #        bash dependencies.sh
  
  building_docker_image:
    runs-on: [self-hosted, git-runner]
    needs: [runner_dependencies]
    steps:
      - name: building docker image
        run: |
         sudo docker build -t shubhamborkar/pythonapp:v1.0 ./
  
  publishing_docker_image:
    runs-on: [self-hosted, git-runner]
    #if: ${{ always() }}        ...runs the job regardless of other jobs being successful
    needs: [runner_dependencies, building_docker_image]
    steps:
      - name: publishing docker image
        run: |
          sudo chmod 666 /var/run/docker.sock
          cat docpasswd.txt | docker login --username shubhamborkar --password-stdin
          sudo docker push shubhamborkar/myapp:v1.0